include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - avoid_print
    - avoid_unnecessary_containers
    - prefer_single_quotes
    - sort_child_properties_last
    - use_key_in_widget_constructors
    - prefer_final_fields
    - unnecessary_this
    - prefer_is_empty
    - prefer_is_not_empty
    - avoid_init_to_null
    - prefer_collection_literals
    - prefer_if_null_operators
    - prefer_null_aware_operators
    - unnecessary_null_in_if_null_operators
    - prefer_conditional_assignment
    - prefer_for_elements_to_map_fromIterable
    - prefer_spread_collections
    - unnecessary_lambdas
    - unnecessary_getters_setters
    - prefer_expression_function_bodies
    - avoid_returning_null_for_void
    - avoid_void_async
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - invariant_booleans
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - prefer_void_to_null
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - unrelated_type_equality_checks
    - valid_regexps

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
